# Generated by Django 5.1.1 on 2024-09-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('DO', 'Done'), ('WD', "Won't Do"), ('BL', 'Blocked')], default='IP', max_length=2)),
                ('created_at', models.DateField(editable=False)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItemPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_amount', models.IntegerField(default=1)),
                ('time_unit', models.CharField(choices=[('D', 'Days'), ('W', 'Weeks'), ('M', 'Months')], default='W', max_length=1)),
            ],
        ),
    ]
