# Generated by Django 5.1.1 on 2024-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
