# Generated by Django 5.0.6 on 2024-06-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
